const tracks = [
  { title: "50 Let Me Off Uptown", file: "music/50 Let Me Off Uptown.mp3" },
  { title: "28 Washington Whiligig", file: "music/28 Washington Whiligig.mp3" },
  { title: "sentimental journey", file: "music/sentimental_journey.mp3" },
  { title: "~ back to regular ~", file: "bits/back_to_regular.mp3" },
  { title: "09 AT THE WOODCHOPPER'S BALL", file: "music/09 AT THE WOODCHOPPER'S BALL.mp3" },
  { title: "49 Frenesi", file: "music/49 Frenesi.mp3" },
  { title: "53 Besame Mucho", file: "music/53 Besame Mucho.mp3" },
  { title: "55 Leap Frog", file: "music/55 Leap Frog.mp3" },
  { title: "22 On the Sunny Side of the Street", file: "music/22 On the Sunny Side of the Street.mp3" },
  { title: "52 Sweet Sue, Just You", file: "music/52 Sweet Sue, Just You.mp3" },
  { title: "~ django intro ~", file: "bits/django_intro.mp3" },
  { title: "08 Embraceable You", file: "music/08 Embraceable You.mp3" },
  { title: "14 I Can't Get Started With You", file: "music/14 I Can't Get Started With You.mp3" },
  { title: "34 Bugle Call Rag", file: "music/34 Bugle Call Rag.mp3" },
  { title: "51 Swinging the Blues", file: "music/51 Swinging the Blues.mp3" },
  { title: "58 The Darktown Strutters' Ball", file: "music/58 The Darktown Strutters' Ball.mp3" },
  { title: "12 WHEN IT'S SLEEPY TIME DOWN SOUTH", file: "music/12 WHEN IT'S SLEEPY TIME DOWN SOUTH.mp3" },
  { title: "~ unearthly newsflash ~", file: "bits/unearthly_newsflash.mp3" },
  { title: "46 Shoo-Fly Pie & Apple Pan Dowdy", file: "music/46 Shoo-Fly Pie & Apple Pan Dowdy.mp3" },
  { title: "29 Green Eyes", file: "music/29 Green Eyes.mp3" },
  { title: "36 Knock Me a Kiss", file: "music/36 Knock Me a Kiss.mp3" },
  { title: "A Morning in the Garden", file: "music/originals/A Morning in the Garden.mp3" },
  { title: "18 In the Mood", file: "music/18 In the Mood.mp3" },
  { title: "dont get around", file: "music/dont_get_around.mp3" },
  { title: "~ WOLD-PM ~", file: "bits/station_id_02.mp3" },
  { title: "65 Moonlight Seranade", file: "music/65 Moonlight Seranade.mp3" },
  { title: "02 Take the A Train", file: "music/02 Take the A Train.mp3" },
  { title: "33 Jumpin at the Woodisde", file: "music/33 Jumpin at the Woodisde.mp3" },
  { title: "63 I'm Gonna Move to the Outskirts of Town", file: "music/63 I'm Gonna Move to the Outskirts of Town.mp3" },
  { title: "~ Illumination-Station-AD ~", file: "bits/Illumination-Station-AD.mp3" },
  { title: "47 I've Got Love to Keep Me Warm", file: "music/47 I've Got Love to Keep Me Warm.mp3" },
  { title: "johnny morgan", file: "music/originals/johnny morgan.mp3" },
  { title: "56 Boog It", file: "music/56 Boog It.mp3" },
  { title: "42 Love for Sale", file: "music/42 Love for Sale.mp3" },
  { title: "03 Begin the Beguine", file: "music/03 Begin the Beguine.mp3" },
  { title: "37 After You've Gone", file: "music/37 After You've Gone.mp3" },
  { title: "~ mannavator ad ~", file: "bits/mannavator_ad.mp3" },
  { title: "57 Coctails for Two", file: "music/57 Coctails for Two.mp3" },
  { title: "45 Caldonia", file: "music/45 Caldonia.mp3" },
  { title: "30 I'm Free (What's New-)", file: "music/30 I'm Free (What's New-).mp3" },
  { title: "~ back to regular ~", file: "bits/back_to_regular.mp3" },
  { title: "48 Don't Get Around Much Anymore", file: "music/48 Don't Get Around Much Anymore.mp3" },
  { title: "60 I Don't Wanna Walk Without You", file: "music/60 I Don't Wanna Walk Without You.mp3" },
  { title: "13 Song of India", file: "music/13 Song of India.mp3" },
  { title: "~ django intro ~", file: "bits/django_intro.mp3" },
  { title: "10 South Rampart Street Parade", file: "music/10 South Rampart Street Parade.mp3" },
  { title: "newsflash", file: "music/newsflash.mp3" },
  { title: "20 Opus 1", file: "music/20 Opus 1.mp3" },
  { title: "~ unearthly newsflash ~", file: "bits/unearthly_newsflash.mp3" },
  { title: "16 Tangerine", file: "music/16 Tangerine.mp3" },
  { title: "62 Echoes of Harlem", file: "music/62 Echoes of Harlem.mp3" },
  { title: "tuxedo junction", file: "music/tuxedo_junction.mp3" },
  { title: "06 Flying Home", file: "music/06 Flying Home.mp3" },
  { title: "39 Midnight Son", file: "music/39 Midnight Son.mp3" },
  { title: "ad", file: "music/ad.mp3" },
  { title: "~ WOLD-PM ~", file: "bits/station_id_01.mp3" },
  { title: "15 I've heard that song before", file: "music/15 I've heard that song before.mp3" },
  { title: "flying home", file: "music/flying_home.mp3" },
  { title: "25 I Let a Song Go Out of My Heart", file: "music/25 I Let a Song Go Out of My Heart.mp3" },
  { title: "07 One o'clock jump", file: "music/07 One o'clock jump.mp3" },
  { title: "43 Windy City Jive", file: "music/43 Windy City Jive.mp3" },
  { title: "~ Illumination-Station-AD ~", file: "bits/Illumination-Station-AD.mp3" },
  { title: "41 Northwest Passage", file: "music/41 Northwest Passage.mp3" },
  { title: "54 Tea for Two", file: "music/54 Tea for Two.mp3" },
  { title: "64 Close to Five", file: "music/64 Close to Five.mp3" },
  { title: "DRUNKEN RAT - Cisco Houston", file: "music/DRUNKEN RAT - Cisco Houston.mp3" },
  { title: "~ mannavator ad ~", file: "bits/mannavator_ad.mp3" },
  { title: "31 Casa Loma Stomp", file: "music/31 Casa Loma Stomp.mp3" },
  { title: "59 Cherokee", file: "music/59 Cherokee.mp3" },
  { title: "AIN'T GONNA BE TREATED THIS WAY - Woody Guthrie", file: "music/AIN'T GONNA BE TREATED THIS WAY - Woody Guthrie.mp3" },
  { title: "~ back to regular ~", file: "bits/back_to_regular.mp3" },
  { title: "04 Blues in the Night", file: "music/04 Blues in the Night.mp3" },
  { title: "38 Little John Special", file: "music/38 Little John Special.mp3" },
  { title: "11 Minnie the Moocher", file: "music/11 Minnie the Moocher.mp3" },
  { title: "19 I Love the Rhythm in a Riff", file: "music/19 I Love the Rhythm in a Riff.mp3" },
  { title: "~ django intro ~", file: "bits/django_intro.mp3" },
  { title: "One More Mile", file: "music/originals/One More Mile.mp3" },
  { title: "32 Harlem Stomp", file: "music/32 Harlem Stomp.mp3" },
  { title: "21 The Peanut Vendor", file: "music/21 The Peanut Vendor.mp3" },
  { title: "~ WOLD-PM ~", file: "bits/station_id_02.mp3" },
  { title: "23 Tuxedo Juction", file: "music/23 Tuxedo Juction.mp3" },
  { title: "27 You Made Me Love You", file: "music/27 You Made Me Love You.mp3" },
  { title: "35 Limehouse Blues", file: "music/35 Limehouse Blues.mp3" },
  { title: "24 Chattanooga Choo Choo", file: "music/24 Chattanooga Choo Choo.mp3" },
  { title: "~ unearthly newsflash ~", file: "bits/unearthly_newsflash.mp3" },
  { title: "17 Sentimental Journey", file: "music/17 Sentimental Journey.mp3" },
  { title: "44 Night & Day", file: "music/44 Night & Day.mp3" },
  { title: "~ Django Reinhardt Special ~", file: "bits/django_intro.mp3" },
  { title: "213 - django reinhardt - crepuscule", file: "shows/DjangoHour/213-django_reinhardt-crepuscule.mp3" },
  { title: "116 - django reinhardt - swingtime in springtime", file: "shows/DjangoHour/116-django_reinhardt-swingtime_in_springtime.mp3" },
  { title: "09. Swing 42", file: "shows/DjangoHour/09. Swing 42.mp3" },
  { title: "07. It’s Only A Paper Moon", file: "shows/DjangoHour/07. It’s Only A Paper Moon.mp3" },
  { title: "02. Beyond The Sea", file: "shows/DjangoHour/02. Beyond The Sea.mp3" },
  { title: "215 - django reinhardt - folie a amphion", file: "shows/DjangoHour/215-django_reinhardt-folie_a_amphion.mp3" },
  { title: "17. Ou Es - Tu Mon Amour？", file: "shows/DjangoHour/17. Ou Es-Tu Mon Amour？.mp3" },
  { title: "201 - django reinhardt - melodie au crepuscule", file: "shows/DjangoHour/201-django_reinhardt-melodie_au_crepuscule.mp3" },
  { title: "218 - django reinhardt - douce ambiance", file: "shows/DjangoHour/218-django_reinhardt-douce_ambiance.mp3" },
  { title: "04. Django Castle (Le Manoir De Mes Reves)", file: "shows/DjangoHour/04. Django Castle (Le Manoir De Mes Reves).mp3" },
  { title: "114 - django reinhardt - confessin", file: "shows/DjangoHour/114-django_reinhardt-confessin.mp3" },
  { title: "118 - django reinhardt - manor de mes reves", file: "shows/DjangoHour/118-django_reinhardt-manor_de_mes_reves.mp3" },
  { title: "117 - django reinhardt - blues in mineur", file: "shows/DjangoHour/117-django_reinhardt-blues_in_mineur.mp3" },
  { title: "101 - django reinhardt - topsy", file: "shows/DjangoHour/101-django_reinhardt-topsy.mp3" },
  { title: "119 - django reinhardt - babik", file: "shows/DjangoHour/119-django_reinhardt-babik.mp3" },
  { title: "04. Jersey Bounce", file: "shows/DjangoHour/04. Jersey Bounce.mp3" },
  { title: "204 - django reinhardt - minor swing", file: "shows/DjangoHour/204-django_reinhardt-minor_swing.mp3" },
  { title: "07. Anniversary Song", file: "shows/DjangoHour/07. Anniversary Song.mp3" },
  { title: "08. I Saw Stars", file: "shows/DjangoHour/08. I Saw Stars.mp3" },
  { title: "15. Saint - Louis Blues", file: "shows/DjangoHour/15. Saint-Louis Blues.mp3" },
  { title: "11. All The Things You Are", file: "shows/DjangoHour/11. All The Things You Are.mp3" },
  { title: "09. Nuages", file: "shows/DjangoHour/09. Nuages.mp3" },
  { title: "211 - django reinhardt - vendredi 13", file: "shows/DjangoHour/211-django_reinhardt-vendredi_13.mp3" },
  { title: "206 - django reinhardt - artillerie lourde", file: "shows/DjangoHour/206-django_reinhardt-artillerie_lourde.mp3" },
  { title: "111 - django reinhardt - danse norvegienne", file: "shows/DjangoHour/111-django_reinhardt-danse_norvegienne.mp3" },
  { title: "214 - django reinhardt - song dautomne", file: "shows/DjangoHour/214-django_reinhardt-song_dautomne.mp3" },
  { title: "202 - django reinhardt - feerie", file: "shows/DjangoHour/202-django_reinhardt-feerie.mp3" },
  { title: "210 - django reinhardt - del salle", file: "shows/DjangoHour/210-django_reinhardt-del_salle.mp3" },
  { title: "10. Swing Guitars", file: "shows/DjangoHour/10. Swing Guitars.mp3" },
  { title: "06. Menilmontant", file: "shows/DjangoHour/06. Menilmontant.mp3" },
  { title: "216 - django reinhardt - swing guitars", file: "shows/DjangoHour/216-django_reinhardt-swing_guitars.mp3" },
  { title: "104 - django reinhardt - brazil", file: "shows/DjangoHour/104-django_reinhardt-brazil.mp3" },
  { title: "05. Dream Of You", file: "shows/DjangoHour/05. Dream Of You.mp3" },
  { title: "107 - django reinhardt - djangos blues", file: "shows/DjangoHour/107-django_reinhardt-djangos_blues.mp3" },
  { title: "212 - django reinhardt - sweet chorus", file: "shows/DjangoHour/212-django_reinhardt-sweet_chorus.mp3" },
  { title: "13. I Got Rhythm", file: "shows/DjangoHour/13. I Got Rhythm.mp3" },
  { title: "01. Minor Swing", file: "shows/DjangoHour/01. Minor Swing.mp3" },
  { title: "12. A Tisket A Tasket", file: "shows/DjangoHour/12. A Tisket A Tasket.mp3" },
  { title: "108 - django reinhardt - mano", file: "shows/DjangoHour/108-django_reinhardt-mano.mp3" },
  { title: "109 - django reinhardt - blues primitif", file: "shows/DjangoHour/109-django_reinhardt-blues_primitif.mp3" },
  { title: "208 - django reinhardt - stockholm", file: "shows/DjangoHour/208-django_reinhardt-stockholm.mp3" },
  { title: "207 - django reinhardt - peche a la mouche", file: "shows/DjangoHour/207-django_reinhardt-peche_a_la_mouche.mp3" },
  { title: "110 - django reinhardt - blues clair", file: "shows/DjangoHour/110-django_reinhardt-blues_clair.mp3" },
  { title: "105 - django reinhardt - anniversary song", file: "shows/DjangoHour/105-django_reinhardt-anniversary_song.mp3" },
  { title: "08. After You’ve Gone", file: "shows/DjangoHour/08. After You’ve Gone.mp3" },
  { title: "106 - django reinhardt - swing 48", file: "shows/DjangoHour/106-django_reinhardt-swing_48.mp3" },
  { title: "03. Marie", file: "shows/DjangoHour/03. Marie.mp3" },
  { title: "16. Djangology", file: "shows/DjangoHour/16. Djangology.mp3" },
  { title: "12. Lover Man (Oh, Where Can You Be)", file: "shows/DjangoHour/12. Lover Man (Oh, Where Can You Be).mp3" },
  { title: "103 - django reinhardt - moppin the bride (micro)", file: "shows/DjangoHour/103-django_reinhardt-moppin_the_bride_(micro).mp3" },
  { title: "10. Stormy Weather", file: "shows/DjangoHour/10. Stormy Weather.mp3" },
  { title: "13. September Song", file: "shows/DjangoHour/13. September Song.mp3" },
  { title: "15. Improvisation On Tchaikowsky’s ''Pathetique'' Andante", file: "shows/DjangoHour/15. Improvisation On Tchaikowsky’s ''Pathetique'' Andante.mp3" },
  { title: "11. Brick Top", file: "shows/DjangoHour/11. Brick Top.mp3" },
  { title: "120 - django reinhardt - swing 39", file: "shows/DjangoHour/120-django_reinhardt-swing_39.mp3" },
  { title: "219 - django reinhardt - swing de paris", file: "shows/DjangoHour/219-django_reinhardt-swing_de_paris.mp3" },
  { title: "113 - django reinhardt - ill never smile again (take 2)", file: "shows/DjangoHour/113-django_reinhardt-ill_never_smile_again_(take_2).mp3" },
  { title: "203 - django reinhardt - dinettte", file: "shows/DjangoHour/203-django_reinhardt-dinettte.mp3" },
  { title: "14. Heavy Artillery (Artillerie Lourde)", file: "shows/DjangoHour/14. Heavy Artillery (Artillerie Lourde).mp3" },
  { title: "18. Russian Songs Medley", file: "shows/DjangoHour/18. Russian Songs Medley.mp3" },
  { title: "16. Sophisticated Lady", file: "shows/DjangoHour/16. Sophisticated Lady.mp3" },
  { title: "17. Darktown Strutter’s Ball", file: "shows/DjangoHour/17. Darktown Strutter’s Ball.mp3" },
  { title: "14. Honeysuckle Rose", file: "shows/DjangoHour/14. Honeysuckle Rose.mp3" },
  { title: "209 - django reinhardt - nuages", file: "shows/DjangoHour/209-django_reinhardt-nuages.mp3" },
  { title: "112 - django reinhardt - blues for barclay (take 1)", file: "shows/DjangoHour/112-django_reinhardt-blues_for_barclay_(take_1).mp3" },
  { title: "18. Royal Garden Blues", file: "shows/DjangoHour/18. Royal Garden Blues.mp3" },
  { title: "05. I Surrender Dear", file: "shows/DjangoHour/05. I Surrender Dear.mp3" },
  { title: "115 - django reinhardt - night and day", file: "shows/DjangoHour/115-django_reinhardt-night_and_day.mp3" },
  { title: "03. The World Is Waiting For The Sunrise", file: "shows/DjangoHour/03. The World Is Waiting For The Sunrise.mp3" },
  { title: "102 - django reinhardt - september song", file: "shows/DjangoHour/102-django_reinhardt-september_song.mp3" },
  { title: "217 - django reinhardt - belleville", file: "shows/DjangoHour/217-django_reinhardt-belleville.mp3" },
  { title: "02. I’ll Never Be The Same", file: "shows/DjangoHour/02. I’ll Never Be The Same.mp3" },
  { title: "06. Halleluyah", file: "shows/DjangoHour/06. Halleluyah.mp3" },
  { title: "01. Daphne", file: "shows/DjangoHour/01. Daphne.mp3" },
  { title: "205 - django reinhardt - swing 41", file: "shows/DjangoHour/205-django_reinhardt-swing_41.mp3" },
  { title: "~ Back to Regular Programming ~", file: "bits/back_to_regular.mp3" },
  { title: "01 Skyliner", file: "music/01 Skyliner.mp3" },
  { title: "~ Illumination-Station-AD ~", file: "bits/Illumination-Station-AD.mp3" },
  { title: "station id", file: "music/station_id.mp3" },
  { title: "40 Tampico", file: "music/40 Tampico.mp3" },
  { title: "05 And the Angels sing", file: "music/05 And the Angels sing.mp3" },
  { title: "26 For Dancers Only", file: "music/26 For Dancers Only.mp3" },
  { title: "moonlight serenade", file: "music/moonlight_serenade.mp3" },
  { title: "~ mannavator ad ~", file: "bits/mannavator_ad.mp3" },
  { title: "61 Since I Fell for You", file: "music/61 Since I Fell for You.mp3" },
  { title: "~ back to regular ~", file: "bits/back_to_regular.mp3" },
];
