const djangoShow = [
  { title: "~ Django Reinhardt Special ~", file: "bits/django_intro.mp3" },
  { title: "213 - django reinhardt - crepuscule", file: "shows/DjangoHour/213-django_reinhardt-crepuscule.mp3" },
  { title: "116 - django reinhardt - swingtime in springtime", file: "shows/DjangoHour/116-django_reinhardt-swingtime_in_springtime.mp3" },
  { title: "09. Swing 42", file: "shows/DjangoHour/09. Swing 42.mp3" },
  { title: "07. It’s Only A Paper Moon", file: "shows/DjangoHour/07. It’s Only A Paper Moon.mp3" },
  { title: "02. Beyond The Sea", file: "shows/DjangoHour/02. Beyond The Sea.mp3" },
  { title: "215 - django reinhardt - folie a amphion", file: "shows/DjangoHour/215-django_reinhardt-folie_a_amphion.mp3" },
  { title: "17. Ou Es - Tu Mon Amour？", file: "shows/DjangoHour/17. Ou Es-Tu Mon Amour？.mp3" },
  { title: "201 - django reinhardt - melodie au crepuscule", file: "shows/DjangoHour/201-django_reinhardt-melodie_au_crepuscule.mp3" },
  { title: "218 - django reinhardt - douce ambiance", file: "shows/DjangoHour/218-django_reinhardt-douce_ambiance.mp3" },
  { title: "04. Django Castle (Le Manoir De Mes Reves)", file: "shows/DjangoHour/04. Django Castle (Le Manoir De Mes Reves).mp3" },
  { title: "114 - django reinhardt - confessin", file: "shows/DjangoHour/114-django_reinhardt-confessin.mp3" },
  { title: "118 - django reinhardt - manor de mes reves", file: "shows/DjangoHour/118-django_reinhardt-manor_de_mes_reves.mp3" },
  { title: "117 - django reinhardt - blues in mineur", file: "shows/DjangoHour/117-django_reinhardt-blues_in_mineur.mp3" },
  { title: "101 - django reinhardt - topsy", file: "shows/DjangoHour/101-django_reinhardt-topsy.mp3" },
  { title: "119 - django reinhardt - babik", file: "shows/DjangoHour/119-django_reinhardt-babik.mp3" },
  { title: "04. Jersey Bounce", file: "shows/DjangoHour/04. Jersey Bounce.mp3" },
  { title: "204 - django reinhardt - minor swing", file: "shows/DjangoHour/204-django_reinhardt-minor_swing.mp3" },
  { title: "07. Anniversary Song", file: "shows/DjangoHour/07. Anniversary Song.mp3" },
  { title: "08. I Saw Stars", file: "shows/DjangoHour/08. I Saw Stars.mp3" },
  { title: "15. Saint - Louis Blues", file: "shows/DjangoHour/15. Saint-Louis Blues.mp3" },
  { title: "11. All The Things You Are", file: "shows/DjangoHour/11. All The Things You Are.mp3" },
  { title: "09. Nuages", file: "shows/DjangoHour/09. Nuages.mp3" },
  { title: "211 - django reinhardt - vendredi 13", file: "shows/DjangoHour/211-django_reinhardt-vendredi_13.mp3" },
  { title: "206 - django reinhardt - artillerie lourde", file: "shows/DjangoHour/206-django_reinhardt-artillerie_lourde.mp3" },
  { title: "111 - django reinhardt - danse norvegienne", file: "shows/DjangoHour/111-django_reinhardt-danse_norvegienne.mp3" },
  { title: "214 - django reinhardt - song dautomne", file: "shows/DjangoHour/214-django_reinhardt-song_dautomne.mp3" },
  { title: "202 - django reinhardt - feerie", file: "shows/DjangoHour/202-django_reinhardt-feerie.mp3" },
  { title: "210 - django reinhardt - del salle", file: "shows/DjangoHour/210-django_reinhardt-del_salle.mp3" },
  { title: "10. Swing Guitars", file: "shows/DjangoHour/10. Swing Guitars.mp3" },
  { title: "06. Menilmontant", file: "shows/DjangoHour/06. Menilmontant.mp3" },
  { title: "216 - django reinhardt - swing guitars", file: "shows/DjangoHour/216-django_reinhardt-swing_guitars.mp3" },
  { title: "104 - django reinhardt - brazil", file: "shows/DjangoHour/104-django_reinhardt-brazil.mp3" },
  { title: "05. Dream Of You", file: "shows/DjangoHour/05. Dream Of You.mp3" },
  { title: "107 - django reinhardt - djangos blues", file: "shows/DjangoHour/107-django_reinhardt-djangos_blues.mp3" },
  { title: "212 - django reinhardt - sweet chorus", file: "shows/DjangoHour/212-django_reinhardt-sweet_chorus.mp3" },
  { title: "13. I Got Rhythm", file: "shows/DjangoHour/13. I Got Rhythm.mp3" },
  { title: "01. Minor Swing", file: "shows/DjangoHour/01. Minor Swing.mp3" },
  { title: "12. A Tisket A Tasket", file: "shows/DjangoHour/12. A Tisket A Tasket.mp3" },
  { title: "108 - django reinhardt - mano", file: "shows/DjangoHour/108-django_reinhardt-mano.mp3" },
  { title: "109 - django reinhardt - blues primitif", file: "shows/DjangoHour/109-django_reinhardt-blues_primitif.mp3" },
  { title: "208 - django reinhardt - stockholm", file: "shows/DjangoHour/208-django_reinhardt-stockholm.mp3" },
  { title: "207 - django reinhardt - peche a la mouche", file: "shows/DjangoHour/207-django_reinhardt-peche_a_la_mouche.mp3" },
  { title: "110 - django reinhardt - blues clair", file: "shows/DjangoHour/110-django_reinhardt-blues_clair.mp3" },
  { title: "105 - django reinhardt - anniversary song", file: "shows/DjangoHour/105-django_reinhardt-anniversary_song.mp3" },
  { title: "08. After You’ve Gone", file: "shows/DjangoHour/08. After You’ve Gone.mp3" },
  { title: "106 - django reinhardt - swing 48", file: "shows/DjangoHour/106-django_reinhardt-swing_48.mp3" },
  { title: "03. Marie", file: "shows/DjangoHour/03. Marie.mp3" },
  { title: "16. Djangology", file: "shows/DjangoHour/16. Djangology.mp3" },
  { title: "12. Lover Man (Oh, Where Can You Be)", file: "shows/DjangoHour/12. Lover Man (Oh, Where Can You Be).mp3" },
  { title: "103 - django reinhardt - moppin the bride (micro)", file: "shows/DjangoHour/103-django_reinhardt-moppin_the_bride_(micro).mp3" },
  { title: "10. Stormy Weather", file: "shows/DjangoHour/10. Stormy Weather.mp3" },
  { title: "13. September Song", file: "shows/DjangoHour/13. September Song.mp3" },
  { title: "15. Improvisation On Tchaikowsky’s ''Pathetique'' Andante", file: "shows/DjangoHour/15. Improvisation On Tchaikowsky’s ''Pathetique'' Andante.mp3" },
  { title: "11. Brick Top", file: "shows/DjangoHour/11. Brick Top.mp3" },
  { title: "120 - django reinhardt - swing 39", file: "shows/DjangoHour/120-django_reinhardt-swing_39.mp3" },
  { title: "219 - django reinhardt - swing de paris", file: "shows/DjangoHour/219-django_reinhardt-swing_de_paris.mp3" },
  { title: "113 - django reinhardt - ill never smile again (take 2)", file: "shows/DjangoHour/113-django_reinhardt-ill_never_smile_again_(take_2).mp3" },
  { title: "203 - django reinhardt - dinettte", file: "shows/DjangoHour/203-django_reinhardt-dinettte.mp3" },
  { title: "14. Heavy Artillery (Artillerie Lourde)", file: "shows/DjangoHour/14. Heavy Artillery (Artillerie Lourde).mp3" },
  { title: "18. Russian Songs Medley", file: "shows/DjangoHour/18. Russian Songs Medley.mp3" },
  { title: "16. Sophisticated Lady", file: "shows/DjangoHour/16. Sophisticated Lady.mp3" },
  { title: "17. Darktown Strutter’s Ball", file: "shows/DjangoHour/17. Darktown Strutter’s Ball.mp3" },
  { title: "14. Honeysuckle Rose", file: "shows/DjangoHour/14. Honeysuckle Rose.mp3" },
  { title: "209 - django reinhardt - nuages", file: "shows/DjangoHour/209-django_reinhardt-nuages.mp3" },
  { title: "112 - django reinhardt - blues for barclay (take 1)", file: "shows/DjangoHour/112-django_reinhardt-blues_for_barclay_(take_1).mp3" },
  { title: "18. Royal Garden Blues", file: "shows/DjangoHour/18. Royal Garden Blues.mp3" },
  { title: "05. I Surrender Dear", file: "shows/DjangoHour/05. I Surrender Dear.mp3" },
  { title: "115 - django reinhardt - night and day", file: "shows/DjangoHour/115-django_reinhardt-night_and_day.mp3" },
  { title: "03. The World Is Waiting For The Sunrise", file: "shows/DjangoHour/03. The World Is Waiting For The Sunrise.mp3" },
  { title: "102 - django reinhardt - september song", file: "shows/DjangoHour/102-django_reinhardt-september_song.mp3" },
  { title: "217 - django reinhardt - belleville", file: "shows/DjangoHour/217-django_reinhardt-belleville.mp3" },
  { title: "02. I’ll Never Be The Same", file: "shows/DjangoHour/02. I’ll Never Be The Same.mp3" },
  { title: "06. Halleluyah", file: "shows/DjangoHour/06. Halleluyah.mp3" },
  { title: "01. Daphne", file: "shows/DjangoHour/01. Daphne.mp3" },
  { title: "205 - django reinhardt - swing 41", file: "shows/DjangoHour/205-django_reinhardt-swing_41.mp3" },
  { title: "~ Back to Regular Programming ~", file: "bits/back_to_regular.mp3" },
];
