const djangoShow1 = [
  { title: "~ Django Reinhardt Special Vol. 1 ~", file: "bits/django_intro.mp3" },
  { title: "01. Daphne", file: "shows/DjangoHour/01. Daphne.mp3" },
  { title: "04. Jersey Bounce", file: "shows/DjangoHour/04. Jersey Bounce.mp3" },
  { title: "11. Brick Top", file: "shows/DjangoHour/11. Brick Top.mp3" },
  { title: "06. Halleluyah", file: "shows/DjangoHour/06. Halleluyah.mp3" },
  { title: "12. Lover Man (Oh, Where Can You Be)", file: "shows/DjangoHour/12. Lover Man (Oh, Where Can You Be).mp3" },
  { title: "10. Stormy Weather", file: "shows/DjangoHour/10. Stormy Weather.mp3" },
  { title: "07. Anniversary Song", file: "shows/DjangoHour/07. Anniversary Song.mp3" },
  { title: "11. All The Things You Are", file: "shows/DjangoHour/11. All The Things You Are.mp3" },
  { title: "202 - django reinhardt - feerie", file: "shows/DjangoHour/202-django_reinhardt-feerie.mp3" },
  { title: "12. A Tisket A Tasket", file: "shows/DjangoHour/12. A Tisket A Tasket.mp3" },
  { title: "07. It’s Only A Paper Moon", file: "shows/DjangoHour/07. It’s Only A Paper Moon.mp3" },
  { title: "14. Heavy Artillery (Artillerie Lourde)", file: "shows/DjangoHour/14. Heavy Artillery (Artillerie Lourde).mp3" },
  { title: "17. Darktown Strutter’s Ball", file: "shows/DjangoHour/17. Darktown Strutter’s Ball.mp3" },
  { title: "15. Improvisation On Tchaikowsky’s ''Pathetique'' Andante", file: "shows/DjangoHour/15. Improvisation On Tchaikowsky’s ''Pathetique'' Andante.mp3" },
  { title: "09. Nuages", file: "shows/DjangoHour/09. Nuages.mp3" },
  { title: "108 - django reinhardt - mano", file: "shows/DjangoHour/108-django_reinhardt-mano.mp3" },
  { title: "203 - django reinhardt - dinettte", file: "shows/DjangoHour/203-django_reinhardt-dinettte.mp3" },
  { title: "117 - django reinhardt - blues in mineur", file: "shows/DjangoHour/117-django_reinhardt-blues_in_mineur.mp3" },
  { title: "116 - django reinhardt - swingtime in springtime", file: "shows/DjangoHour/116-django_reinhardt-swingtime_in_springtime.mp3" },
  { title: "102 - django reinhardt - september song", file: "shows/DjangoHour/102-django_reinhardt-september_song.mp3" },
  { title: "111 - django reinhardt - danse norvegienne", file: "shows/DjangoHour/111-django_reinhardt-danse_norvegienne.mp3" },
  { title: "09. Swing 42", file: "shows/DjangoHour/09. Swing 42.mp3" },
  { title: "201 - django reinhardt - melodie au crepuscule", file: "shows/DjangoHour/201-django_reinhardt-melodie_au_crepuscule.mp3" },
  { title: "118 - django reinhardt - manor de mes reves", file: "shows/DjangoHour/118-django_reinhardt-manor_de_mes_reves.mp3" },
  { title: "110 - django reinhardt - blues clair", file: "shows/DjangoHour/110-django_reinhardt-blues_clair.mp3" },
  { title: "03. The World Is Waiting For The Sunrise", file: "shows/DjangoHour/03. The World Is Waiting For The Sunrise.mp3" },
  { title: "211 - django reinhardt - vendredi 13", file: "shows/DjangoHour/211-django_reinhardt-vendredi_13.mp3" },
  { title: "05. Dream Of You", file: "shows/DjangoHour/05. Dream Of You.mp3" },
  { title: "106 - django reinhardt - swing 48", file: "shows/DjangoHour/106-django_reinhardt-swing_48.mp3" },
  { title: "03. Marie", file: "shows/DjangoHour/03. Marie.mp3" },
  { title: "~ Back to Regular Programming ~", file: "bits/back_to_regular.mp3" },
];
