const djangoShow2 = [
  { title: "~ Django Reinhardt Special Vol. 2 ~", file: "bits/django_intro.mp3" },
  { title: "18. Russian Songs Medley", file: "shows/DjangoHour/18. Russian Songs Medley.mp3" },
  { title: "08. I Saw Stars", file: "shows/DjangoHour/08. I Saw Stars.mp3" },
  { title: "107 - django reinhardt - djangos blues", file: "shows/DjangoHour/107-django_reinhardt-djangos_blues.mp3" },
  { title: "05. I Surrender Dear", file: "shows/DjangoHour/05. I Surrender Dear.mp3" },
  { title: "119 - django reinhardt - babik", file: "shows/DjangoHour/119-django_reinhardt-babik.mp3" },
  { title: "213 - django reinhardt - crepuscule", file: "shows/DjangoHour/213-django_reinhardt-crepuscule.mp3" },
  { title: "18. Royal Garden Blues", file: "shows/DjangoHour/18. Royal Garden Blues.mp3" },
  { title: "17. Ou Es - Tu Mon Amour？", file: "shows/DjangoHour/17. Ou Es-Tu Mon Amour？.mp3" },
  { title: "16. Djangology", file: "shows/DjangoHour/16. Djangology.mp3" },
  { title: "14. Honeysuckle Rose", file: "shows/DjangoHour/14. Honeysuckle Rose.mp3" },
  { title: "01. Minor Swing", file: "shows/DjangoHour/01. Minor Swing.mp3" },
  { title: "206 - django reinhardt - artillerie lourde", file: "shows/DjangoHour/206-django_reinhardt-artillerie_lourde.mp3" },
  { title: "105 - django reinhardt - anniversary song", file: "shows/DjangoHour/105-django_reinhardt-anniversary_song.mp3" },
  { title: "16. Sophisticated Lady", file: "shows/DjangoHour/16. Sophisticated Lady.mp3" },
  { title: "104 - django reinhardt - brazil", file: "shows/DjangoHour/104-django_reinhardt-brazil.mp3" },
  { title: "218 - django reinhardt - douce ambiance", file: "shows/DjangoHour/218-django_reinhardt-douce_ambiance.mp3" },
  { title: "115 - django reinhardt - night and day", file: "shows/DjangoHour/115-django_reinhardt-night_and_day.mp3" },
  { title: "113 - django reinhardt - ill never smile again (take 2)", file: "shows/DjangoHour/113-django_reinhardt-ill_never_smile_again_(take_2).mp3" },
  { title: "02. I’ll Never Be The Same", file: "shows/DjangoHour/02. I’ll Never Be The Same.mp3" },
  { title: "216 - django reinhardt - swing guitars", file: "shows/DjangoHour/216-django_reinhardt-swing_guitars.mp3" },
  { title: "103 - django reinhardt - moppin the bride (micro)", file: "shows/DjangoHour/103-django_reinhardt-moppin_the_bride_(micro).mp3" },
  { title: "207 - django reinhardt - peche a la mouche", file: "shows/DjangoHour/207-django_reinhardt-peche_a_la_mouche.mp3" },
  { title: "208 - django reinhardt - stockholm", file: "shows/DjangoHour/208-django_reinhardt-stockholm.mp3" },
  { title: "15. Saint - Louis Blues", file: "shows/DjangoHour/15. Saint-Louis Blues.mp3" },
  { title: "06. Menilmontant", file: "shows/DjangoHour/06. Menilmontant.mp3" },
  { title: "214 - django reinhardt - song dautomne", file: "shows/DjangoHour/214-django_reinhardt-song_dautomne.mp3" },
  { title: "217 - django reinhardt - belleville", file: "shows/DjangoHour/217-django_reinhardt-belleville.mp3" },
  { title: "204 - django reinhardt - minor swing", file: "shows/DjangoHour/204-django_reinhardt-minor_swing.mp3" },
  { title: "13. September Song", file: "shows/DjangoHour/13. September Song.mp3" },
  { title: "215 - django reinhardt - folie a amphion", file: "shows/DjangoHour/215-django_reinhardt-folie_a_amphion.mp3" },
  { title: "~ Back to Regular Programming ~", file: "bits/back_to_regular.mp3" },
];
