const djangoShow3 = [
  { title: "~ Django Reinhardt Special Vol. 3 ~", file: "bits/django_intro.mp3" },
  { title: "205 - django reinhardt - swing 41", file: "shows/DjangoHour/205-django_reinhardt-swing_41.mp3" },
  { title: "08. After You’ve Gone", file: "shows/DjangoHour/08. After You’ve Gone.mp3" },
  { title: "04. Django Castle (Le Manoir De Mes Reves)", file: "shows/DjangoHour/04. Django Castle (Le Manoir De Mes Reves).mp3" },
  { title: "114 - django reinhardt - confessin", file: "shows/DjangoHour/114-django_reinhardt-confessin.mp3" },
  { title: "101 - django reinhardt - topsy", file: "shows/DjangoHour/101-django_reinhardt-topsy.mp3" },
  { title: "219 - django reinhardt - swing de paris", file: "shows/DjangoHour/219-django_reinhardt-swing_de_paris.mp3" },
  { title: "10. Swing Guitars", file: "shows/DjangoHour/10. Swing Guitars.mp3" },
  { title: "02. Beyond The Sea", file: "shows/DjangoHour/02. Beyond The Sea.mp3" },
  { title: "120 - django reinhardt - swing 39", file: "shows/DjangoHour/120-django_reinhardt-swing_39.mp3" },
  { title: "209 - django reinhardt - nuages", file: "shows/DjangoHour/209-django_reinhardt-nuages.mp3" },
  { title: "13. I Got Rhythm", file: "shows/DjangoHour/13. I Got Rhythm.mp3" },
  { title: "109 - django reinhardt - blues primitif", file: "shows/DjangoHour/109-django_reinhardt-blues_primitif.mp3" },
  { title: "112 - django reinhardt - blues for barclay (take 1)", file: "shows/DjangoHour/112-django_reinhardt-blues_for_barclay_(take_1).mp3" },
  { title: "210 - django reinhardt - del salle", file: "shows/DjangoHour/210-django_reinhardt-del_salle.mp3" },
  { title: "212 - django reinhardt - sweet chorus", file: "shows/DjangoHour/212-django_reinhardt-sweet_chorus.mp3" },
  { title: "~ Back to Regular Programming ~", file: "bits/back_to_regular.mp3" },
];
