const djangoShow3 = [
  { title: "~ Django Reinhardt Special Vol. 3 ~", file: "bits/django_intro.mp3" },
  { title: "212 - django reinhardt - sweet chorus", file: "shows/DjangoHour/212-django_reinhardt-sweet_chorus.mp3" },
  { title: "105 - django reinhardt - anniversary song", file: "shows/DjangoHour/105-django_reinhardt-anniversary_song.mp3" },
  { title: "04. Jersey Bounce", file: "shows/DjangoHour/04. Jersey Bounce.mp3" },
  { title: "10. Stormy Weather", file: "shows/DjangoHour/10. Stormy Weather.mp3" },
  { title: "13. September Song", file: "shows/DjangoHour/13. September Song.mp3" },
  { title: "17. Ou Es - Tu Mon Amour？", file: "shows/DjangoHour/17. Ou Es-Tu Mon Amour？.mp3" },
  { title: "106 - django reinhardt - swing 48", file: "shows/DjangoHour/106-django_reinhardt-swing_48.mp3" },
  { title: "12. Lover Man (Oh, Where Can You Be)", file: "shows/DjangoHour/12. Lover Man (Oh, Where Can You Be).mp3" },
  { title: "03. The World Is Waiting For The Sunrise", file: "shows/DjangoHour/03. The World Is Waiting For The Sunrise.mp3" },
  { title: "05. I Surrender Dear", file: "shows/DjangoHour/05. I Surrender Dear.mp3" },
  { title: "116 - django reinhardt - swingtime in springtime", file: "shows/DjangoHour/116-django_reinhardt-swingtime_in_springtime.mp3" },
  { title: "214 - django reinhardt - song dautomne", file: "shows/DjangoHour/214-django_reinhardt-song_dautomne.mp3" },
  { title: "06. Menilmontant", file: "shows/DjangoHour/06. Menilmontant.mp3" },
  { title: "12. A Tisket A Tasket", file: "shows/DjangoHour/12. A Tisket A Tasket.mp3" },
  { title: "04. Django Castle (Le Manoir De Mes Reves)", file: "shows/DjangoHour/04. Django Castle (Le Manoir De Mes Reves).mp3" },
  { title: "~ Back to Regular Programming ~", file: "bits/back_to_regular.mp3" },
];
