const djangoShow2 = [
  { title: "~ Django Reinhardt Special Vol. 2 ~", file: "bits/django_intro.mp3" },
  { title: "104 - django reinhardt - brazil", file: "shows/DjangoHour/104-django_reinhardt-brazil.mp3" },
  { title: "117 - django reinhardt - blues in mineur", file: "shows/DjangoHour/117-django_reinhardt-blues_in_mineur.mp3" },
  { title: "11. Brick Top", file: "shows/DjangoHour/11. Brick Top.mp3" },
  { title: "213 - django reinhardt - crepuscule", file: "shows/DjangoHour/213-django_reinhardt-crepuscule.mp3" },
  { title: "218 - django reinhardt - douce ambiance", file: "shows/DjangoHour/218-django_reinhardt-douce_ambiance.mp3" },
  { title: "06. Halleluyah", file: "shows/DjangoHour/06. Halleluyah.mp3" },
  { title: "109 - django reinhardt - blues primitif", file: "shows/DjangoHour/109-django_reinhardt-blues_primitif.mp3" },
  { title: "208 - django reinhardt - stockholm", file: "shows/DjangoHour/208-django_reinhardt-stockholm.mp3" },
  { title: "08. I Saw Stars", file: "shows/DjangoHour/08. I Saw Stars.mp3" },
  { title: "202 - django reinhardt - feerie", file: "shows/DjangoHour/202-django_reinhardt-feerie.mp3" },
  { title: "07. Anniversary Song", file: "shows/DjangoHour/07. Anniversary Song.mp3" },
  { title: "201 - django reinhardt - melodie au crepuscule", file: "shows/DjangoHour/201-django_reinhardt-melodie_au_crepuscule.mp3" },
  { title: "11. All The Things You Are", file: "shows/DjangoHour/11. All The Things You Are.mp3" },
  { title: "09. Nuages", file: "shows/DjangoHour/09. Nuages.mp3" },
  { title: "217 - django reinhardt - belleville", file: "shows/DjangoHour/217-django_reinhardt-belleville.mp3" },
  { title: "16. Djangology", file: "shows/DjangoHour/16. Djangology.mp3" },
  { title: "206 - django reinhardt - artillerie lourde", file: "shows/DjangoHour/206-django_reinhardt-artillerie_lourde.mp3" },
  { title: "216 - django reinhardt - swing guitars", file: "shows/DjangoHour/216-django_reinhardt-swing_guitars.mp3" },
  { title: "09. Swing 42", file: "shows/DjangoHour/09. Swing 42.mp3" },
  { title: "02. Beyond The Sea", file: "shows/DjangoHour/02. Beyond The Sea.mp3" },
  { title: "15. Improvisation On Tchaikowsky’s ''Pathetique'' Andante", file: "shows/DjangoHour/15. Improvisation On Tchaikowsky’s ''Pathetique'' Andante.mp3" },
  { title: "112 - django reinhardt - blues for barclay (take 1)", file: "shows/DjangoHour/112-django_reinhardt-blues_for_barclay_(take_1).mp3" },
  { title: "114 - django reinhardt - confessin", file: "shows/DjangoHour/114-django_reinhardt-confessin.mp3" },
  { title: "05. Dream Of You", file: "shows/DjangoHour/05. Dream Of You.mp3" },
  { title: "101 - django reinhardt - topsy", file: "shows/DjangoHour/101-django_reinhardt-topsy.mp3" },
  { title: "103 - django reinhardt - moppin the bride (micro)", file: "shows/DjangoHour/103-django_reinhardt-moppin_the_bride_(micro).mp3" },
  { title: "14. Honeysuckle Rose", file: "shows/DjangoHour/14. Honeysuckle Rose.mp3" },
  { title: "102 - django reinhardt - september song", file: "shows/DjangoHour/102-django_reinhardt-september_song.mp3" },
  { title: "16. Sophisticated Lady", file: "shows/DjangoHour/16. Sophisticated Lady.mp3" },
  { title: "108 - django reinhardt - mano", file: "shows/DjangoHour/108-django_reinhardt-mano.mp3" },
  { title: "~ Back to Regular Programming ~", file: "bits/back_to_regular.mp3" },
];
