const djangoShow1 = [
  { title: "~ Django Reinhardt Special Vol. 1 ~", file: "bits/django_intro.mp3" },
  { title: "110 - django reinhardt - blues clair", file: "shows/DjangoHour/110-django_reinhardt-blues_clair.mp3" },
  { title: "205 - django reinhardt - swing 41", file: "shows/DjangoHour/205-django_reinhardt-swing_41.mp3" },
  { title: "01. Minor Swing", file: "shows/DjangoHour/01. Minor Swing.mp3" },
  { title: "209 - django reinhardt - nuages", file: "shows/DjangoHour/209-django_reinhardt-nuages.mp3" },
  { title: "107 - django reinhardt - djangos blues", file: "shows/DjangoHour/107-django_reinhardt-djangos_blues.mp3" },
  { title: "118 - django reinhardt - manor de mes reves", file: "shows/DjangoHour/118-django_reinhardt-manor_de_mes_reves.mp3" },
  { title: "02. I’ll Never Be The Same", file: "shows/DjangoHour/02. I’ll Never Be The Same.mp3" },
  { title: "01. Daphne", file: "shows/DjangoHour/01. Daphne.mp3" },
  { title: "10. Swing Guitars", file: "shows/DjangoHour/10. Swing Guitars.mp3" },
  { title: "18. Royal Garden Blues", file: "shows/DjangoHour/18. Royal Garden Blues.mp3" },
  { title: "119 - django reinhardt - babik", file: "shows/DjangoHour/119-django_reinhardt-babik.mp3" },
  { title: "18. Russian Songs Medley", file: "shows/DjangoHour/18. Russian Songs Medley.mp3" },
  { title: "14. Heavy Artillery (Artillerie Lourde)", file: "shows/DjangoHour/14. Heavy Artillery (Artillerie Lourde).mp3" },
  { title: "03. Marie", file: "shows/DjangoHour/03. Marie.mp3" },
  { title: "07. It’s Only A Paper Moon", file: "shows/DjangoHour/07. It’s Only A Paper Moon.mp3" },
  { title: "17. Darktown Strutter’s Ball", file: "shows/DjangoHour/17. Darktown Strutter’s Ball.mp3" },
  { title: "115 - django reinhardt - night and day", file: "shows/DjangoHour/115-django_reinhardt-night_and_day.mp3" },
  { title: "203 - django reinhardt - dinettte", file: "shows/DjangoHour/203-django_reinhardt-dinettte.mp3" },
  { title: "204 - django reinhardt - minor swing", file: "shows/DjangoHour/204-django_reinhardt-minor_swing.mp3" },
  { title: "13. I Got Rhythm", file: "shows/DjangoHour/13. I Got Rhythm.mp3" },
  { title: "113 - django reinhardt - ill never smile again (take 2)", file: "shows/DjangoHour/113-django_reinhardt-ill_never_smile_again_(take_2).mp3" },
  { title: "120 - django reinhardt - swing 39", file: "shows/DjangoHour/120-django_reinhardt-swing_39.mp3" },
  { title: "219 - django reinhardt - swing de paris", file: "shows/DjangoHour/219-django_reinhardt-swing_de_paris.mp3" },
  { title: "111 - django reinhardt - danse norvegienne", file: "shows/DjangoHour/111-django_reinhardt-danse_norvegienne.mp3" },
  { title: "215 - django reinhardt - folie a amphion", file: "shows/DjangoHour/215-django_reinhardt-folie_a_amphion.mp3" },
  { title: "211 - django reinhardt - vendredi 13", file: "shows/DjangoHour/211-django_reinhardt-vendredi_13.mp3" },
  { title: "210 - django reinhardt - del salle", file: "shows/DjangoHour/210-django_reinhardt-del_salle.mp3" },
  { title: "15. Saint - Louis Blues", file: "shows/DjangoHour/15. Saint-Louis Blues.mp3" },
  { title: "207 - django reinhardt - peche a la mouche", file: "shows/DjangoHour/207-django_reinhardt-peche_a_la_mouche.mp3" },
  { title: "08. After You’ve Gone", file: "shows/DjangoHour/08. After You’ve Gone.mp3" },
  { title: "~ Back to Regular Programming ~", file: "bits/back_to_regular.mp3" },
];
